theme: jekyll-theme-slate

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# title: VendGuard
# description: Smart Health Monitoring System for Vending Machines
# show_downloads: false
